name: jkn
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4

  # 追加ライブラリ
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.8
  firebase_storage: ^10.2.7
  bubbled_navigation_bar: ^0.0.3
  flutter_launcher_icons: ^0.9.2
  flutter_chat_ui: ^1.5.5
  provider: ^6.0.2
  uuid: ^3.0.6
  image_picker: ^0.8.4+9
  image_picker_for_web: ^2.1.6
  firebase_auth: ^3.3.7
  firebase_auth_web: ^3.3.7
  file_picker: ^4.4.0
  flutter_firebase_chat_core: ^1.5.2
  mime: ^1.0.1
  open_file: ^3.2.1
  path_provider: ^2.0.9
  faker: ^2.0.0
  font_awesome_flutter: ^9.0.0-nullsafet
  collapsible_sidebar: ^2.0.1+2
  foldable_sidebar: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon/icon.png"

flutter:

  uses-material-design: true

  # assets:
  #   - assets/icon.png